# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\TASK1_Final\Main_Program_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1810, 944)
        MainWindow.setStyleSheet("background: rgba(56, 63, 79, 1);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 1771, 901))
        self.label.setStyleSheet("background-color:rgba(85, 101, 128, 0.7);\n"
"border-radius:20px;\n"
"border: 2px solid white;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.ComboBox_Top_Signals = QtWidgets.QComboBox(self.centralwidget)
        self.ComboBox_Top_Signals.setGeometry(QtCore.QRect(1590, 120, 171, 31))
        self.ComboBox_Top_Signals.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ComboBox_Top_Signals.setObjectName("ComboBox_Top_Signals")
        self.CheckBox_API = QtWidgets.QCheckBox(self.centralwidget)
        self.CheckBox_API.setGeometry(QtCore.QRect(210, 50, 121, 41))
        self.CheckBox_API.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.CheckBox_API.setObjectName("CheckBox_API")
        self.ToolButton_Middle_ZoomIn = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButton_Middle_ZoomIn.setGeometry(QtCore.QRect(420, 870, 41, 31))
        self.ToolButton_Middle_ZoomIn.setStyleSheet("  background: white;\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  font-size: 14px;\n"
"  color:black;\n"
"  border: 3px solid black;\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_Middle_ZoomIn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("zoomin.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.ToolButton_Middle_ZoomIn.setIcon(icon)
        self.ToolButton_Middle_ZoomIn.setIconSize(QtCore.QSize(24, 24))
        self.ToolButton_Middle_ZoomIn.setObjectName("ToolButton_Middle_ZoomIn")
        self.ToolButton_Top_ZoomOut = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButton_Top_ZoomOut.setGeometry(QtCore.QRect(470, 480, 41, 31))
        self.ToolButton_Top_ZoomOut.setStyleSheet("  background: white;\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  font-size: 14px;\n"
"  color:black;\n"
"  border: 3px solid black;\n"
"  border-radius: 0.4em;\n"
"  \n"
"\n"
"")
        self.ToolButton_Top_ZoomOut.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("zoomout.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.ToolButton_Top_ZoomOut.setIcon(icon1)
        self.ToolButton_Top_ZoomOut.setIconSize(QtCore.QSize(24, 24))
        self.ToolButton_Top_ZoomOut.setObjectName("ToolButton_Top_ZoomOut")
        self.ToolButton_Top_ZoomIn = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButton_Top_ZoomIn.setGeometry(QtCore.QRect(420, 480, 41, 31))
        self.ToolButton_Top_ZoomIn.setStyleSheet("  background: white;\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  font-size: 14px;\n"
"  color:black;\n"
"  border: 3px solid black;\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_Top_ZoomIn.setText("")
        self.ToolButton_Top_ZoomIn.setIcon(icon)
        self.ToolButton_Top_ZoomIn.setIconSize(QtCore.QSize(24, 24))
        self.ToolButton_Top_ZoomIn.setObjectName("ToolButton_Top_ZoomIn")
        self.ToolButton_Middle_PlayPause = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButton_Middle_PlayPause.setGeometry(QtCore.QRect(60, 870, 91, 31))
        self.ToolButton_Middle_PlayPause.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_Middle_PlayPause.setObjectName("ToolButton_Middle_PlayPause")
        self.LineEdit_Middle_EditLabel = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_Middle_EditLabel.setGeometry(QtCore.QRect(1430, 820, 149, 34))
        self.LineEdit_Middle_EditLabel.setStyleSheet("  background-color: #212121;\n"
"  max-width: 190px;\n"
"  color:white;\n"
"  height: 20px;\n"
"  padding: 5px;\n"
"  border: 2px solid white;\n"
"  border-radius: 5px;\n"
"  ")
        self.LineEdit_Middle_EditLabel.setText("")
        self.LineEdit_Middle_EditLabel.setObjectName("LineEdit_Middle_EditLabel")
        self.ToolButton_Top_Replay = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButton_Top_Replay.setGeometry(QtCore.QRect(160, 480, 101, 31))
        self.ToolButton_Top_Replay.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  font-size: 14px;\n"
"  color:black;\n"
"  border: 3px solid black;\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_Top_Replay.setObjectName("ToolButton_Top_Replay")
        self.ToolButton_MoveUp = QtWidgets.QPushButton(self.centralwidget)
        self.ToolButton_MoveUp.setGeometry(QtCore.QRect(1430, 740, 149, 31))
        self.ToolButton_MoveUp.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_MoveUp.setObjectName("ToolButton_MoveUp")
        self.ToolButton_SwitchGraphs = QtWidgets.QPushButton(self.centralwidget)
        self.ToolButton_SwitchGraphs.setGeometry(QtCore.QRect(350, 50, 151, 41))
        self.ToolButton_SwitchGraphs.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_SwitchGraphs.setObjectName("ToolButton_SwitchGraphs")
        self.ToolButton_CreatePdf = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButton_CreatePdf.setGeometry(QtCore.QRect(520, 50, 151, 41))
        self.ToolButton_CreatePdf.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_CreatePdf.setObjectName("ToolButton_CreatePdf")
        self.ToolButton_Middle_Replay = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButton_Middle_Replay.setGeometry(QtCore.QRect(170, 870, 91, 31))
        self.ToolButton_Middle_Replay.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  font-size: 14px;\n"
"  border: 3px solid black;\n"
"  border-radius: 0.4em;\n"
"\n"
"")
        self.ToolButton_Middle_Replay.setObjectName("ToolButton_Middle_Replay")
        self.checkBox_Middle_ShowHide = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Middle_ShowHide.setGeometry(QtCore.QRect(1430, 540, 151, 31))
        self.checkBox_Middle_ShowHide.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.checkBox_Middle_ShowHide.setObjectName("checkBox_Middle_ShowHide")
        self.ToolButton_MoveDown = QtWidgets.QPushButton(self.centralwidget)
        self.ToolButton_MoveDown.setGeometry(QtCore.QRect(1430, 320, 151, 31))
        self.ToolButton_MoveDown.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_MoveDown.setObjectName("ToolButton_MoveDown")
        self.ComboBox_Middle_Signals = QtWidgets.QComboBox(self.centralwidget)
        self.ComboBox_Middle_Signals.setGeometry(QtCore.QRect(1590, 540, 171, 31))
        self.ComboBox_Middle_Signals.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ComboBox_Middle_Signals.setObjectName("ComboBox_Middle_Signals")
        self.ToolButton_Top_Browse = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButton_Top_Browse.setEnabled(True)
        self.ToolButton_Top_Browse.setGeometry(QtCore.QRect(1430, 160, 151, 32))
        self.ToolButton_Top_Browse.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_Top_Browse.setObjectName("ToolButton_Top_Browse")
        self.checkBox_Top_ShowHide = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_Top_ShowHide.setGeometry(QtCore.QRect(1430, 120, 151, 31))
        self.checkBox_Top_ShowHide.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.checkBox_Top_ShowHide.setObjectName("checkBox_Top_ShowHide")
        self.ToolButton_Middle_Delete = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButton_Middle_Delete.setGeometry(QtCore.QRect(1430, 620, 151, 32))
        self.ToolButton_Middle_Delete.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_Middle_Delete.setObjectName("ToolButton_Middle_Delete")
        self.ToolButton_SecondWindow = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButton_SecondWindow.setGeometry(QtCore.QRect(860, 50, 151, 41))
        self.ToolButton_SecondWindow.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_SecondWindow.setObjectName("ToolButton_SecondWindow")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 110, 1361, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Widget_Top = PlotWidget(self.verticalLayoutWidget)
        self.Widget_Top.setStyleSheet("background: Black;\n"
"border: 2px solid white;\n"
"border-radius:20px;\n"
"")
        self.Widget_Top.setObjectName("Widget_Top")
        self.verticalLayout.addWidget(self.Widget_Top)
        self.ComboBox_ConcatenateGraph = QtWidgets.QComboBox(self.centralwidget)
        self.ComboBox_ConcatenateGraph.setGeometry(QtCore.QRect(1030, 50, 149, 41))
        self.ComboBox_ConcatenateGraph.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ComboBox_ConcatenateGraph.setObjectName("ComboBox_ConcatenateGraph")
        self.ComboBox_ConcatenateGraph.addItem("")
        self.ComboBox_ConcatenateGraph.addItem("")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(60, 530, 1361, 301))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Widget_Middle = PlotWidget(self.verticalLayoutWidget_3)
        self.Widget_Middle.setStyleSheet("background: Black;\n"
"border: 2px solid white;\n"
"border-radius:20px;\n"
"")
        self.Widget_Middle.setObjectName("Widget_Middle")
        self.verticalLayout_8.addWidget(self.Widget_Middle)
        self.ToolButton_Top_Delete = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButton_Top_Delete.setEnabled(True)
        self.ToolButton_Top_Delete.setGeometry(QtCore.QRect(1430, 200, 151, 32))
        self.ToolButton_Top_Delete.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_Top_Delete.setObjectName("ToolButton_Top_Delete")
        self.CheckBox_LinkGraphs = QtWidgets.QCheckBox(self.centralwidget)
        self.CheckBox_LinkGraphs.setGeometry(QtCore.QRect(70, 50, 121, 41))
        self.CheckBox_LinkGraphs.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.CheckBox_LinkGraphs.setObjectName("CheckBox_LinkGraphs")
        self.ComboBox_InterpolationOrder = QtWidgets.QComboBox(self.centralwidget)
        self.ComboBox_InterpolationOrder.setGeometry(QtCore.QRect(1200, 50, 149, 41))
        self.ComboBox_InterpolationOrder.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ComboBox_InterpolationOrder.setObjectName("ComboBox_InterpolationOrder")
        self.ComboBox_InterpolationOrder.addItem("")
        self.ComboBox_InterpolationOrder.addItem("")
        self.ComboBox_InterpolationOrder.addItem("")
        self.ComboBox_InterpolationOrder.addItem("")
        self.ToolButton_Middle_SelectPart = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButton_Middle_SelectPart.setGeometry(QtCore.QRect(1430, 660, 151, 32))
        self.ToolButton_Middle_SelectPart.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_Middle_SelectPart.setObjectName("ToolButton_Middle_SelectPart")
        self.LineEdit_Top_EditLabel = QtWidgets.QLineEdit(self.centralwidget)
        self.LineEdit_Top_EditLabel.setGeometry(QtCore.QRect(1430, 400, 151, 34))
        self.LineEdit_Top_EditLabel.setStyleSheet("  background-color: #212121;\n"
"  max-width: 190px;\n"
"  color:white;\n"
"  height: 20px;\n"
"  padding: 5px;\n"
"  border: 2px solid white;\n"
"  border-radius: 5px;\n"
"")
        self.LineEdit_Top_EditLabel.setText("")
        self.LineEdit_Top_EditLabel.setObjectName("LineEdit_Top_EditLabel")
        self.ToolButton_Middle_SelectColor = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButton_Middle_SelectColor.setGeometry(QtCore.QRect(1430, 700, 151, 32))
        self.ToolButton_Middle_SelectColor.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_Middle_SelectColor.setObjectName("ToolButton_Middle_SelectColor")
        self.ToolButton_Top_PlayPause = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButton_Top_PlayPause.setGeometry(QtCore.QRect(50, 480, 91, 31))
        self.ToolButton_Top_PlayPause.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_Top_PlayPause.setObjectName("ToolButton_Top_PlayPause")
        self.ToolButton_ConcatnateGraphs = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButton_ConcatnateGraphs.setGeometry(QtCore.QRect(690, 50, 151, 41))
        self.ToolButton_ConcatnateGraphs.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_ConcatnateGraphs.setObjectName("ToolButton_ConcatnateGraphs")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1030, 20, 149, 30))
        self.label_4.setStyleSheet("  font-weight: 600;\n"
"background-color:rgba(85, 101, 128, 0.7);\n"
"border-top:2px solid white;\n"
"  color:white;\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.ToolButton_Middle_TakeSnapShot = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButton_Middle_TakeSnapShot.setGeometry(QtCore.QRect(280, 870, 121, 31))
        self.ToolButton_Middle_TakeSnapShot.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_Middle_TakeSnapShot.setObjectName("ToolButton_Middle_TakeSnapShot")
        self.ToolButton_Top_SelectPart = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButton_Top_SelectPart.setGeometry(QtCore.QRect(1430, 240, 151, 32))
        self.ToolButton_Top_SelectPart.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_Top_SelectPart.setObjectName("ToolButton_Top_SelectPart")
        self.HorizontalSlider_Top_connectGraphs = QtWidgets.QSlider(self.centralwidget)
        self.HorizontalSlider_Top_connectGraphs.setGeometry(QtCore.QRect(1030, 490, 391, 22))
        self.HorizontalSlider_Top_connectGraphs.setStyleSheet("\n"
"background-color:rgba(85, 101, 128, 0.7);\n"
"\n"
"\n"
"\n"
"")
        self.HorizontalSlider_Top_connectGraphs.setPageStep(1)
        self.HorizontalSlider_Top_connectGraphs.setOrientation(QtCore.Qt.Horizontal)
        self.HorizontalSlider_Top_connectGraphs.setObjectName("HorizontalSlider_Top_connectGraphs")
        self.HorizontalSlider_Middle_connectGraphs = QtWidgets.QSlider(self.centralwidget)
        self.HorizontalSlider_Middle_connectGraphs.setGeometry(QtCore.QRect(1040, 880, 381, 22))
        self.HorizontalSlider_Middle_connectGraphs.setStyleSheet("\n"
"background-color:rgba(85, 101, 128, 0.7);\n"
"\n"
"")
        self.HorizontalSlider_Middle_connectGraphs.setPageStep(1)
        self.HorizontalSlider_Middle_connectGraphs.setOrientation(QtCore.Qt.Horizontal)
        self.HorizontalSlider_Middle_connectGraphs.setObjectName("HorizontalSlider_Middle_connectGraphs")
        self.ToolButton_Top_SelectColor = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButton_Top_SelectColor.setGeometry(QtCore.QRect(1430, 280, 151, 32))
        self.ToolButton_Top_SelectColor.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_Top_SelectColor.setObjectName("ToolButton_Top_SelectColor")
        self.ToolButton_Middle_ZoomOut = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButton_Middle_ZoomOut.setGeometry(QtCore.QRect(470, 870, 41, 31))
        self.ToolButton_Middle_ZoomOut.setStyleSheet("  background: white;\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  font-size: 14px;\n"
"  color:black;\n"
"  border: 3px solid black;\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_Middle_ZoomOut.setText("")
        self.ToolButton_Middle_ZoomOut.setIcon(icon1)
        self.ToolButton_Middle_ZoomOut.setIconSize(QtCore.QSize(24, 24))
        self.ToolButton_Middle_ZoomOut.setObjectName("ToolButton_Middle_ZoomOut")
        self.ToolButton_Top_TakeSnapShot = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButton_Top_TakeSnapShot.setGeometry(QtCore.QRect(280, 480, 121, 31))
        self.ToolButton_Top_TakeSnapShot.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_Top_TakeSnapShot.setObjectName("ToolButton_Top_TakeSnapShot")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setEnabled(False)
        self.label_5.setGeometry(QtCore.QRect(1200, 20, 149, 31))
        self.label_5.setStyleSheet("  font-weight: 600;\n"
"background-color:rgba(85, 101, 128, 0.7);\n"
"border-top:2px solid white;\n"
"  color:white;\n"
"\n"
"")
        self.label_5.setObjectName("label_5")
        self.ToolButton_Middle_Browse = QtWidgets.QToolButton(self.centralwidget)
        self.ToolButton_Middle_Browse.setGeometry(QtCore.QRect(1430, 580, 151, 32))
        self.ToolButton_Middle_Browse.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_Middle_Browse.setObjectName("ToolButton_Middle_Browse")
        self.verticalScrollBar_Top = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar_Top.setGeometry(QtCore.QRect(40, 109, 16, 331))
        self.verticalScrollBar_Top.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_Top.setObjectName("verticalScrollBar_Top")
        self.horizontalScrollBar_Top = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar_Top.setGeometry(QtCore.QRect(40, 446, 1381, 20))
        self.horizontalScrollBar_Top.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_Top.setObjectName("horizontalScrollBar_Top")
        self.verticalScrollBar_Middle = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar_Middle.setGeometry(QtCore.QRect(40, 530, 16, 311))
        self.verticalScrollBar_Middle.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_Middle.setObjectName("verticalScrollBar_Middle")
        self.horizontalScrollBar_Middle = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar_Middle.setGeometry(QtCore.QRect(40, 840, 1381, 20))
        self.horizontalScrollBar_Middle.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_Middle.setObjectName("horizontalScrollBar_Middle")
        self.horizontalSlider_Middle_Speed = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_Middle_Speed.setGeometry(QtCore.QRect(1590, 780, 171, 31))
        self.horizontalSlider_Middle_Speed.setStyleSheet("\n"
"background-color:rgba(85, 101, 128, 0.7);\n"
"\n"
"\n"
"\n"
"")
        self.horizontalSlider_Middle_Speed.setMinimum(10)
        self.horizontalSlider_Middle_Speed.setMaximum(100)
        self.horizontalSlider_Middle_Speed.setSingleStep(5)
        self.horizontalSlider_Middle_Speed.setPageStep(5)
        self.horizontalSlider_Middle_Speed.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Middle_Speed.setObjectName("horizontalSlider_Middle_Speed")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setEnabled(False)
        self.label_6.setGeometry(QtCore.QRect(1430, 360, 149, 31))
        self.label_6.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setEnabled(False)
        self.label_7.setGeometry(QtCore.QRect(1430, 780, 149, 31))
        self.label_7.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.label_7.setObjectName("label_7")
        self.horizontalSlider_Top_Speed = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_Top_Speed.setGeometry(QtCore.QRect(1590, 360, 171, 31))
        self.horizontalSlider_Top_Speed.setStyleSheet("\n"
"background-color:rgba(85, 101, 128, 0.7);\n"
"\n"
"\n"
"\n"
"")
        self.horizontalSlider_Top_Speed.setMinimum(10)
        self.horizontalSlider_Top_Speed.setMaximum(100)
        self.horizontalSlider_Top_Speed.setSingleStep(5)
        self.horizontalSlider_Top_Speed.setPageStep(5)
        self.horizontalSlider_Top_Speed.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_Top_Speed.setObjectName("horizontalSlider_Top_Speed")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.ComboBox_ConcatenateGraph.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CheckBox_API.setText(_translate("MainWindow", "API"))
        self.ToolButton_Middle_PlayPause.setText(_translate("MainWindow", "Run"))
        self.LineEdit_Middle_EditLabel.setPlaceholderText(_translate("MainWindow", "Enter Label"))
        self.ToolButton_Top_Replay.setText(_translate("MainWindow", "replay"))
        self.ToolButton_MoveUp.setText(_translate("MainWindow", "Move Up"))
        self.ToolButton_SwitchGraphs.setText(_translate("MainWindow", "Switch Graphs"))
        self.ToolButton_CreatePdf.setText(_translate("MainWindow", "Create Pdf"))
        self.ToolButton_Middle_Replay.setText(_translate("MainWindow", "replay"))
        self.checkBox_Middle_ShowHide.setText(_translate("MainWindow", "Hide"))
        self.ToolButton_MoveDown.setText(_translate("MainWindow", "Move Down"))
        self.ToolButton_Top_Browse.setText(_translate("MainWindow", "Choose signal"))
        self.checkBox_Top_ShowHide.setText(_translate("MainWindow", "Hide"))
        self.ToolButton_Middle_Delete.setText(_translate("MainWindow", "Delete signal "))
        self.ToolButton_SecondWindow.setText(_translate("MainWindow", "Second Window"))
        self.ComboBox_ConcatenateGraph.setCurrentText(_translate("MainWindow", "Middle Graph"))
        self.ComboBox_ConcatenateGraph.setItemText(0, _translate("MainWindow", "Top Graph"))
        self.ComboBox_ConcatenateGraph.setItemText(1, _translate("MainWindow", "Middle Graph"))
        self.ToolButton_Top_Delete.setText(_translate("MainWindow", "Delete signal"))
        self.CheckBox_LinkGraphs.setText(_translate("MainWindow", "Link Graphs"))
        self.ComboBox_InterpolationOrder.setItemText(0, _translate("MainWindow", "Nearest"))
        self.ComboBox_InterpolationOrder.setItemText(1, _translate("MainWindow", "Linear"))
        self.ComboBox_InterpolationOrder.setItemText(2, _translate("MainWindow", "Quadratic"))
        self.ComboBox_InterpolationOrder.setItemText(3, _translate("MainWindow", "Cubic"))
        self.ToolButton_Middle_SelectPart.setText(_translate("MainWindow", "Select Part"))
        self.LineEdit_Top_EditLabel.setPlaceholderText(_translate("MainWindow", "Enter Label"))
        self.ToolButton_Middle_SelectColor.setText(_translate("MainWindow", "select color"))
        self.ToolButton_Top_PlayPause.setText(_translate("MainWindow", "Run"))
        self.ToolButton_ConcatnateGraphs.setText(_translate("MainWindow", "Connect Graphs"))
        self.label_4.setText(_translate("MainWindow", "Choose Graph"))
        self.ToolButton_Middle_TakeSnapShot.setText(_translate("MainWindow", "SnapShot"))
        self.ToolButton_Top_SelectPart.setText(_translate("MainWindow", "Select Part"))
        self.ToolButton_Top_SelectColor.setText(_translate("MainWindow", "select color"))
        self.ToolButton_Top_TakeSnapShot.setText(_translate("MainWindow", "SnapShot"))
        self.label_5.setText(_translate("MainWindow", "Interpolation Order"))
        self.ToolButton_Middle_Browse.setText(_translate("MainWindow", "Choose signal"))
        self.label_6.setText(_translate("MainWindow", "Change Speed"))
        self.label_7.setText(_translate("MainWindow", "Change Speed"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
