# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Bassant.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1007, 726)
        Form.setStyleSheet("background: rgba(56, 63, 79, 1);\n"
"")
        self.ToolButton_Rewind = QtWidgets.QToolButton(Form)
        self.ToolButton_Rewind.setGeometry(QtCore.QRect(170, 660, 121, 31))
        self.ToolButton_Rewind.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_Rewind.setObjectName("ToolButton_Rewind")
        self.ToolButton_PlayPause = QtWidgets.QToolButton(Form)
        self.ToolButton_PlayPause.setGeometry(QtCore.QRect(56, 660, 101, 31))
        self.ToolButton_PlayPause.setStyleSheet("  background: rgba(192, 200, 212, 1);\n"
"  font-family: inherit;\n"
"  padding: 0.2em 0.3em;\n"
"  font-weight: 600;\n"
"  color:rgba(34, 38, 49, 1);\n"
"  font-size: 14px;\n"
"  border: 3px solid rgba(34, 38, 49, 1);\n"
"  border-radius: 0.4em;\n"
"  \n"
"")
        self.ToolButton_PlayPause.setObjectName("ToolButton_PlayPause")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 30, 921, 601))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ToolButton_Rewind.setText(_translate("Form", "rewind"))
        self.ToolButton_PlayPause.setText(_translate("Form", "play"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
